# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ModelInfoGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BrandNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.BrandNameLabel.setGeometry(QtCore.QRect(30, 30, 100, 20))
        self.BrandNameLabel.setScaledContents(False)
        self.BrandNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.BrandNameLabel.setObjectName("BrandNameLabel")
        self.BrandPicLabel = QtWidgets.QLabel(self.centralwidget)
        self.BrandPicLabel.setGeometry(QtCore.QRect(30, 50, 100, 100))
        self.BrandPicLabel.setText("")
        self.BrandPicLabel.setPixmap(QtGui.QPixmap(""))
        self.BrandPicLabel.setScaledContents(True)
        self.BrandPicLabel.setObjectName("BrandPicLabel")
        self.BrandInfoButton = QtWidgets.QPushButton(self.centralwidget)
        self.BrandInfoButton.setGeometry(QtCore.QRect(30, 150, 100, 30))
        self.BrandInfoButton.setObjectName("BrandInfoButton")
        self.ModelPicLabel = QtWidgets.QLabel(self.centralwidget)
        self.ModelPicLabel.setGeometry(QtCore.QRect(470, 50, 300, 300))
        self.ModelPicLabel.setText("")
        self.ModelPicLabel.setPixmap(QtGui.QPixmap(""))
        self.ModelPicLabel.setScaledContents(False)
        self.ModelPicLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ModelPicLabel.setObjectName("ModelPicLabel")
        self.ModelNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.ModelNameLabel.setGeometry(QtCore.QRect(470, 30, 300, 20))
        self.ModelNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ModelNameLabel.setObjectName("ModelNameLabel")
        self.SpecTable = QtWidgets.QTableWidget(self.centralwidget)
        self.SpecTable.setGeometry(QtCore.QRect(30, 220, 400, 350))
        self.SpecTable.setObjectName("SpecTable")
        self.SpecTable.setColumnCount(0)
        self.SpecTable.setRowCount(0)
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(550, 370, 135, 60))
        self.BackButton.setObjectName("BackButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BrandNameLabel.setText(_translate("MainWindow", "Имя Бренда"))
        self.BrandInfoButton.setText(_translate("MainWindow", "Информация"))
        self.ModelNameLabel.setText(_translate("MainWindow", "Имя модели"))
        self.BackButton.setText(_translate("MainWindow", "Назад"))
